routes/web.php
<?php


//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'PostController@index')->name('home');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');

Route::resource('posts', 'PostController');

Route::get('/', ['as' => 'index', 'uses' => 'HomeController@getIndex']);
Route::group(['middleware' => 'guest'], function() {
    Route::get('/login', ['as' => 'login', 'uses' => 'HomeController@getLoginPage']);
    Route::post('/login', ['as' => 'attempt_login', 'uses' => 'HomeController@attemptLogin']);
});


Route::group(['middleware' => 'auth'], function() {
    Route::get('/logout', ['as' => 'logout', 'uses' => 'HomeController@logout']);
    Route::get('/dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@getDashboard']);
    Route::group(['prefix' => 'unit', 'middleware' => 'mainUnit'], function() {
        //Unit
        Route::get('/list-unit', ['as' => 'list_unit', 'uses' => 'UnitController@listUnit']);
        Route::get('/add-unit', ['as' => 'add_unit', 'uses' => 'UnitController@addUnit']);
        Route::post('/save-unit', ['as' => 'save_unit', 'uses' => 'UnitController@saveUnit']);
        Route::get('/view-unit/{id}', ['as' => 'view_unit', 'uses' => 'UnitController@viewUnit']);
        Route::get('/edit-unit/{id}', ['as' => 'edit_unit', 'uses' => 'UnitController@editUnit']);
        Route::post('/update-unit/{id}', ['as' => 'update_unit', 'uses' => 'UnitController@updateUnit']);
        Route::get('/unpublish-unit/{id}', ['as' => 'unpublish_unit', 'uses' => 'UnitController@unpublishUnit']);
        Route::get('/publish-unit/{id}', ['as' => 'publish_unit', 'uses' => 'UnitController@publishUnit']);
        Route::get('/delete-unit/{id}', ['as' => 'delete_unit', 'uses' => 'UnitController@deleteUnit']);
    });
    //Employee
    Route::group(['prefix' => 'employee'], function() {
        //Employee
        Route::get('/list-employee', ['as' => 'list_employee', 'uses' => 'EmployeeController@listEmployee']);
        Route::get('/add-employee', ['as' => 'add_employee', 'uses' => 'EmployeeController@addEmployee']);
        Route::post('/save-employee', ['as' => 'save_employee', 'uses' => 'EmployeeController@saveEmployee']);
        Route::get('/view-employee/{id}', ['as' => 'view_employee', 'uses' => 'EmployeeController@viewEmployee']);
        Route::get('/edit-employee/{id}', ['as' => 'edit_employee', 'uses' => 'EmployeeController@editEmployee']);
        Route::post('/update-employee/{id}', ['as' => 'update_employee', 'uses' => 'EmployeeController@updateEmployee']);
        Route::get('/unpublish-employee/{id}', ['as' => 'unpublish_employee', 'uses' => 'EmployeeController@unpublishEmployee']);
        Route::get('/publish-employee/{id}', ['as' => 'publish_employee', 'uses' => 'EmployeeController@publishEmployee']);
        Route::get('/delete-employee/{id}', ['as' => 'delete_employee', 'uses' => 'EmployeeController@deleteEmployee']);
    });
    //Stock
    Route::group(['prefix' => 'stock'], function() {
        Route::get('/list-stock', ['as' => 'list_stock', 'uses' => 'StockController@listStock']);
        Route::get('/list-stock-sub', ['as' => 'list_stock_sub', 'uses' => 'StockController@listStockSub']);
        Route::get('/add-stock', ['as' => 'add_stock', 'uses' => 'StockController@addStock']);
        Route::post('/save-stock', ['as' => 'save_stock', 'uses' => 'StockController@saveStock']);
        Route::get('/edit-stock/{id}', ['as' => 'edit_stock', 'uses' => 'StockController@editStock']);
        Route::post('/update-stock/{id}', ['as' => 'update_stock', 'uses' => 'StockController@updateStock']);
        Route::get('/unpublish-stock/{id}', ['as' => 'unpublish_stock', 'uses' => 'StockController@unpublishStock']);
        Route::get('/publish-stock/{id}', ['as' => 'publish_stock', 'uses' => 'StockController@publishStock']);
        Route::get('/delete-stock/{id}', ['as' => 'delete_stock', 'uses' => 'StockController@deleteStock']);
    });

    Route::group(['prefix' => 'items'], function(){
        //Product
        Route::group(['prefix' => 'product'], function() {
            Route::get('/list-product', ['as' => 'list_product', 'uses' => 'ProductController@listProduct']);
            Route::get('/add-product', ['as' => 'add_product', 'uses' => 'ProductController@addProduct']);
            Route::post('/save-product', ['as' => 'save_product', 'uses' => 'ProductController@saveProduct']);
            Route::get('/edit-product/{id}', ['as' => 'edit_product', 'uses' => 'ProductController@editProduct']);
            Route::get('/view-product/{id}', ['as' => 'view_product', 'uses' => 'ProductController@viewProduct']);
            Route::post('/update-product/{id}', ['as' => 'update_product', 'uses' => 'ProductController@updateProduct']);
            Route::get('/unpublish-product/{id}', ['as' => 'unpublish_product', 'uses' => 'ProductController@unpublishProduct']);
            Route::get('/publish-product/{id}', ['as' => 'publish_product', 'uses' => 'ProductController@publishProduct']);
            Route::get('/delete-product/{id}', ['as' => 'delete_product', 'uses' => 'ProductController@deleteProduct']);
            Route::get('/get-product-by-id/{id}', ['as' => 'get_product_by_id', 'uses' => 'ProductController@getProductById']);
        });
        
        //Product Category
        Route::group(['prefix' => 'category'], function() {
            Route::get('/list-product-category', ['as' => 'list_product_category', 'uses' => 'ProductCategoryController@listProductCategory']);
            Route::get('/add-product-category', ['as' => 'add_product_category', 'uses' => 'ProductCategoryController@addProductCategory']);
            Route::post('/save-product-category', ['as' => 'save_product_category', 'uses' => 'ProductCategoryController@saveProductCategory']);
            Route::get('/edit-product-category/{id}', ['as' => 'edit_product_category', 'uses' => 'ProductCategoryController@editProductCategory']);
            Route::post('/update-product-category/{id}', ['as' => 'update_product_category', 'uses' => 'ProductCategoryController@updateProductCategory']);
            Route::get('/unpublish-product-category/{id}', ['as' => 'unpublish_product_category', 'uses' => 'ProductCategoryController@unpublishProductCategory']);
            Route::get('/publish-product-category/{id}', ['as' => 'publish_product_category', 'uses' => 'ProductCategoryController@publishProductCategory']);
            Route::get('/delete-product-category/{id}', ['as' => 'delete_product_category', 'uses' => 'ProductCategoryController@deleteProductCategory']);
            Route::get('/get-product-category-by-id/{id}', ['as' => 'get_product_category_by_id', 'uses' => 'ProductCategoryController@getProductCategoryById']);
        });
        //Product Brand
        Route::group(['prefix' => 'brand'], function() {
            Route::get('/list-product-brand', ['as' => 'list_product_brand', 'uses' => 'ProductBrandController@listProductBrand']);
            Route::get('/add-product-brand', ['as' => 'add_product_brand', 'uses' => 'ProductBrandController@addProductBrand']);
            Route::post('/save-product-brand', ['as' => 'save_product_brand', 'uses' => 'ProductBrandController@saveProductBrand']);
            Route::get('/edit-product-brand/{id}', ['as' => 'edit_product_brand', 'uses' => 'ProductBrandController@editProductBrand']);
            Route::post('/update-product-brand/{id}', ['as' => 'update_product_brand', 'uses' => 'ProductBrandController@updateProductBrand']);
            Route::get('/unpublish-product-brand/{id}', ['as' => 'unpublish_product_brand', 'uses' => 'ProductBrandController@unpublishProductBrand']);
            Route::get('/publish-product-brand/{id}', ['as' => 'publish_product_brand', 'uses' => 'ProductBrandController@publishProductBrand']);
            Route::get('/delete-product-brand/{id}', ['as' => 'delete_product_brand', 'uses' => 'ProductBrandController@deleteProductBrand']);
            Route::get('/get-product-brand-by-id/{id}', ['as' => 'get_product_brand_by_id', 'uses' => 'ProductBrandController@getProductBrandById']);
        });
    });

    //Demand
    Route::group(['prefix' => 'demand'], function() {
        Route::get('/demand-request-sub', ['as' => 'demand_request_sub', 'uses' => 'DemandController@demandRequestSub'])->middleware('subUnit');
        Route::get('/demand-request-main', ['as' => 'demand_request_main', 'uses' => 'DemandController@demandRequestMain'])->middleware('mainUnit');
        Route::post('/save-pre-demand', ['as' => 'save_pre_demand', 'uses' => 'DemandController@savePreDemand']);
        Route::get('/remove-pre-demand-item/{id}', ['as' => 'remove_pre_demand_item', 'uses' => 'DemandController@removePreDemandItem']);
        Route::get('/remove-pre-demand', ['as' => 'remove_pre_demand', 'uses' => 'DemandController@removePreDemand']);
        Route::get('/save-demand', ['as' => 'save_demand', 'uses' => 'DemandController@saveDemand']);
        Route::get('/view-demand/{demand_no}', ['as' => 'view_demand', 'uses' => 'DemandController@viewDemand']);
        Route::get('/demand-approval/{demand_no}', ['as' => 'demand_approval', 'uses' => 'DemandController@demandApproval']);
        Route::post('/save-demand-approval/{demand_id}', ['as' => 'save_demand_approval', 'uses' => 'DemandController@saveDemandApproval']);
    });
    
    //Distribution
    Route::group(['prefix' => 'distribution', 'middleware' => 'mainUnit'], function(){
        Route::get('/list-distribution-main', ['as' => 'list_distribution_main', 'uses' => 'DistributionController@listDistributionMain']);
        Route::get('/distribution-main/{demand_no}', ['as' => 'distribution_main', 'uses' => 'DistributionController@distributionMain']);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable {

    use SoftDeletes;
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'username', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($password) {
        $this->attributes['password'] = bcrypt($password);
    }

    public function branch() {
        return $this->belongsToMany('App\Unit', 'user_has_branch', 'user_id', 'branch_id');
    }

    public function setBranch($branch_id) {
        $branch = Unit::find($branch_id);
        $this->branch()->save($branch);
        return $this;
    }
    public function updateBranch($branch_id) {
        $this->branch()->detach();
        return $this->setBranch($branch_id);
    }
    public function unit_id()
    {
        return $this->branch()->first()->id;
    }
    public function unit_name()
    {
        return $this->branch()->first()->unit_name;
    }
    public function unit_type()
    {
        return $this->branch()->first()->unit_type;
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Unit;
use Auth;
//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
//Enables us to output flash messaging
use Session;

class UserController extends Controller {

    public function __construct() {
        $this->middleware(['auth', 'isAdmin']); //isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        Session::put('menu', 'users');
        //Get all users and pass it to the view
        $users = User::all();
        return view('users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //Get all roles and pass it to the view
        $roles = Role::get();
        $units = Unit::get();
        return view('users.create', ['roles' => $roles, 'units' => $units]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //Validate name, email and password fields
        $this->validate($request, [
            'name' => 'required|max:120',
            'username' => 'required|unique:users',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:4|confirmed'
        ]);
        $user = User::create($request->only('email', 'username', 'name', 'password')); //Retrieving only the email and password data
        $user->setBranch($request->branch_id);
        $roles = $request['roles']; //Retrieving the roles field
        //Checking if a role was selected
        if (isset($roles)) {

            foreach ($roles as $role) {
                $role_r = Role::where('id', '=', $role)->firstOrFail();
                $user->assignRole($role_r); //Assigning role to user
            }
        }
        //Redirect to the users.index view and display message
        return redirect()->route('users.index')
                        ->with('flash_message', 'User successfully added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        return redirect('users');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $user = User::findOrFail($id); //Get user with specified id
        $branch = $user->branch()->first();
        $roles = Role::get(); //Get all roles
        $units = Unit::get();
        return view('users.edit', compact('user', 'branch', 'roles', 'units')); //pass user and roles data to view
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $user = User::findOrFail($id); //Get role specified by id
        //Validate name, email and password fields  
        $this->validate($request, [
            'name' => 'required|max:120',
            'email' => 'required|email|unique:users,email,' . $id,
        ]);
        $input = $request->only(['name', 'username', 'email']); //Retreive the name, email and password fields
        $roles = $request['roles']; //Retreive all roles
        $user->fill($input)->update();
        $user->updateBranch($request->branch_id);
        if (isset($roles)) {
            $user->roles()->sync($roles);  //If one or more role is selected associate user to roles          
        } else {
            $user->roles()->detach(); //If no role is selected remove exisiting role associated to a user
        }
        return redirect()->route('users.index')
                        ->with('flash_message', 'User successfully edited.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //Find a user with a given id and delete
        $user = User::findOrFail($id);
        if($user->id == Auth::id()){
            Session::put('alert-danger', 'You can\'t delete your own account');
            return redirect()->back();
        }
        $user->delete();

        return redirect()->route('users.index')
                        ->with('flash_message', 'User successfully deleted.');
    }

}

resources/views/users/create.blade.php
@extends('layout')
@section('after_style')
<!-- Select2 -->
<link rel="stylesheet" href="{{asset('public/asset/plugins/select2/select2.min.css')}}">
@endsection

@section('content')

<div class='box'>

    <div class="box-header">
        <h1><i class='fa fa-user-plus'></i> Add User</h1>
        <hr>
    </div>
    @include('partials/messages')
    {{ Form::open(array('url' => 'users')) }}
    <div class="box-body">
        <div class="form-group">
            {{ Form::label('name', 'Name') }}
            {{ Form::text('name', '', array('class' => 'form-control')) }}
        </div>

        <div class="form-group">
            {{ Form::label('email', 'Email') }}
            {{ Form::email('email', '', array('class' => 'form-control')) }}
        </div>
        
        <div class="form-group">
            {{ Form::label('username', 'Username') }}
            {{ Form::text('username', '', array('class' => 'form-control')) }}
        </div>

        <div class='form-group'>
            @foreach ($roles as $role)
            {{ Form::checkbox('roles[]',  $role->id ) }}
            {{ Form::label($role->name, ucfirst($role->name)) }}<br>

            @endforeach
        </div>

        <div class="form-group">
            {{ Form::label('password', 'Password') }}<br>
            {{ Form::password('password', array('class' => 'form-control')) }}

        </div>

        <div class="form-group">
            {{ Form::label('password', 'Confirm Password') }}<br>
            {{ Form::password('password_confirmation', array('class' => 'form-control')) }}

        </div>
        <div class="form-group">
            <label class="control-label">Select Branch</label>
            <select class="form-control select2" name="branch_id">
                @foreach($units as $unit)
                <option value="{{$unit->id}}">{{$unit->unit_name}}</option>
                @endforeach
            </select>
        </div>

    </div>

    <div class="box-footer">
        {{ Form::submit('Save', array('class' => 'btn btn-success')) }}
        <a href="{{route('users.index')}}" class="btn btn-default">Cancel</a>
    </div>

    {{ Form::close() }}

</div>

@endsection

@section('after_script')
<script src="{{asset('public/asset/plugins/select2/select2.full.min.js')}}"></script>
<script>
$(function () {
    //Initialize Select2 Elements
    $(".select2").select2();
});
</script>

@endsection

resources/views/users/edit.blade.php
@extends('layout')
@section('after_style')
<link rel="stylesheet" href="{{asset('public/health/plugins/datatables/dataTables.bootstrap.css')}}">
@endsection

@section('content')

<div class='box'>

    <div class="box-header">
        <h1><i class='fa fa-user-plus'></i> Edit {{$user->name}}</h1>
        <hr>
    </div>
    @include('partials/messages')
    {{ Form::model($user, array('route' => array('users.update', $user->id), 'method' => 'PUT')) }}{{-- Form model binding to automatically populate our fields with user data --}}
    <div class="box-body">

        <div class="form-group">
            {{ Form::label('name', 'Name') }}
            {{ Form::text('name', null, array('class' => 'form-control')) }}
        </div>
        <div class="form-group">
            {{ Form::label('email', 'Email') }}
            {{ Form::email('email', null, array('class' => 'form-control')) }}
        </div>
        
        <div class="form-group">
            {{ Form::label('username', 'Username') }}
            {{ Form::text('username', null, array('class' => 'form-control')) }}
        </div>

        <h5><b>Give Role</b></h5>

        <div class='form-group'>
            @foreach ($roles as $role)
            {{ Form::checkbox('roles[]',  $role->id, $user->roles ) }}
            {{ Form::label($role->name, ucfirst($role->name)) }}<br>

            @endforeach
        </div>

        <div class="form-group">
            <label class="control-label">Select Branch</label>
            <select class="form-control select2" name="branch_id">
                @foreach($units as $unit)
                <option value="{{$unit->id}}" {{$unit->id == $branch->id ? 'selected':''}}>{{$unit->unit_name}}</option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="box-footer">
        {{ Form::submit('Save', array('class' => 'btn btn-success')) }}
        <a href="{{route('users.index')}}" class="btn btn-default">Cancel</a>
    </div>

    {{ Form::close() }}

</div>

@endsection

resources/views/users/index.blade.php
@extends('layout')
@section('after_style')
<link rel="stylesheet" href="{{asset('public/asset/plugins/datatables/dataTables.bootstrap.css')}}">
@endsection

@section('content')

<div class="box">
    <div class="box-header">
        <h1><i class="fa fa-users"></i> User Administration <a href="{{ route('roles.index') }}" class="btn btn-default btn-xs pull-right">Roles</a>
            <a href="{{ route('permissions.index') }}" class="btn btn-default btn-xs pull-right">Permissions</a></h1>
        <hr>
    </div>
    @include('partials/messages')
    <div class="box-body">
        <table class="table table-bordered table-striped data-table">

            <thead>
                <tr>
                    <th>Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Unit</th>
                    <th>User Roles</th>
                    <th>Operations</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($users as $user)
                <tr>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->username }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ str_replace(['[', ']', '"'], '', $user->branch()->pluck('unit_name')) }}</td>
                    <td>{{  $user->roles()->pluck('name')->implode(' ') }}</td>{{-- Retrieve array of roles associated to a user and convert to string --}}
                    <td>
                        <a href="{{ route('users.edit', $user->id) }}" class="btn btn-info pull-left" style="margin-right: 3px;">Edit</a>

                        {!! Form::open(['method' => 'DELETE', 'route' => ['users.destroy', $user->id] ]) !!}
                        {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                        {!! Form::close() !!}

                    </td>
                </tr>
                @endforeach
            </tbody>

        </table>
    </div>
    <div class="box-footer">
        <a href="{{ route('users.create') }}" class="btn btn-success">Add User</a>
    </div>

</div>

@endsection
@section('after_script')
<script src="{{asset('public/asset/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/asset/plugins/datatables/dataTables.bootstrap.min.js')}}"></script>
<script>
$(function () {
    $('.data-table').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": true,
        "ordering": true,
        "info": true,
        "autoWidth": false
    });
});
</script>
@endsection